// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import { combineImportEntries, defaultImportEntries } from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { useEffect } from 'react';
import React from 'react';
import { Placeholder, Text, Link, useSitecore, RichText, CdpHelper } from '@sitecore-content-sdk/nextjs';
import { GraphQLRequestClient } from '@sitecore-content-sdk/nextjs/client';
import scConfig from 'sitecore.config';
import { gql } from 'graphql-request';
import { HelloWorld } from 'src/NonSitecoreComponents/HelloWorld';
import Head from 'next/head';
import client from 'lib/sitecore-client';
import Image from 'next/image';
import * as FEAAS from '@sitecore-feaas/clientside/react';
import nextConfig from 'next.config';
import { pageView } from '@sitecore-cloudsdk/events/browser';

const importMap = [
  {
    module: 'react',
    exports: [
      { name: 'useEffect', value: useEffect },
      { name: 'default', value: React },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Placeholder', value: Placeholder },
      { name: 'Text', value: Text },
      { name: 'Link', value: Link },
      { name: 'useSitecore', value: useSitecore },
      { name: 'RichText', value: RichText },
      { name: 'CdpHelper', value: CdpHelper },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs/client',
    exports: [
      { name: 'GraphQLRequestClient', value: GraphQLRequestClient },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: scConfig },
    ]
  },
  {
    module: 'graphql-request',
    exports: [
      { name: 'gql', value: gql },
    ]
  },
  {
    module: 'src/NonSitecoreComponents/HelloWorld',
    exports: [
      { name: 'HelloWorld', value: HelloWorld },
    ]
  },
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: 'lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image },
    ]
  },
  {
    module: '@sitecore-feaas/clientside/react',
    exports: [
      { name: '*', value: FEAAS },
    ]
  },
  {
    module: 'next.config',
    exports: [
      { name: 'default', value: nextConfig },
    ]
  },
  {
    module: '@sitecore-cloudsdk/events/browser',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  }
];

export default combineImportEntries(defaultImportEntries, importMap);
